// Generated from Exomem 0.19.1 `build_gateway_contract()`; semantic fields only.
export type ExomemContractCommandFixture = readonly [
  name: string,
  readOnly: boolean,
  mode: "read" | "write",
  tier: number,
  capability: string,
  params: readonly (readonly [name: string, type: string, required: boolean])[],
  guardedFields: readonly string[],
];

const commands = [
  ["coordination_status", true, "read", 1, "core", [], []],
  [
    "bootstrap",
    true,
    "read",
    1,
    "core",
    [
      ["profile", "str", false],
      ["workflow", "str", false],
    ],
    [],
  ],
  [
    "ask_memory",
    true,
    "read",
    1,
    "core",
    [
      ["query", "str", false],
      ["types", "list[str]", false],
      ["projects", "list[str]", false],
      ["tags", "list[str]", false],
      ["speakers", "list[str]", false],
      ["file_types", "list[str]", false],
      ["exclude_file_types", "list[str]", false],
      ["limit", "int", false],
      ["scope", "str", false],
      ["mode", "str", false],
      ["detail", "str", false],
      ["deep", "bool", false],
      ["graph", "bool", false],
      ["rerank", "bool", false],
      ["prefer_compiled", "bool", false],
      ["prefer_active", "bool", false],
      ["prefer_used", "bool", false],
      ["graph_enrich", "bool", false],
      ["include_timings", "bool", false],
    ],
    [],
  ],
  [
    "read_memory",
    true,
    "read",
    1,
    "core",
    [
      ["path", "str", true],
      ["frontmatter_only", "bool", false],
      ["include_history", "bool", false],
      ["links", "bool", false],
      ["include_raw", "bool", false],
    ],
    [],
  ],
  [
    "browse_memory",
    true,
    "read",
    1,
    "core",
    [
      ["path", "str", false],
      ["mode", "str", false],
      ["max_depth", "int", false],
      ["include_hidden", "bool", false],
      ["samples", "int", false],
      ["recursive", "bool", false],
    ],
    [],
  ],
  [
    "remember",
    false,
    "write",
    1,
    "core",
    [
      ["content", "str", true],
      ["title", "str", true],
      ["slug", "str", false],
      ["note_type", "str", false],
      ["project", "str", false],
      ["projects", "list[str]", false],
      ["sources", "list[str]", false],
      ["tags", "list[str]", false],
      ["status", "str", false],
      ["severity", "str", false],
      ["pattern_type", "str", false],
      ["domain", "str", false],
      ["started", "str", false],
      ["duration", "str", false],
      ["hypothesis", "str", false],
      ["n", "int", false],
      ["concluded", "str", false],
      ["medium", "str", false],
      ["recorded", "str", false],
      ["published", "str", false],
      ["host", "str", false],
      ["editor", "str", false],
      ["suggestions", "bool", false],
      ["project_category", "str", false],
    ],
    ["content"],
  ],
  [
    "edit_memory",
    false,
    "write",
    1,
    "core",
    [
      ["path", "str", true],
      ["why", "str", true],
      ["new_body", "str", false],
      ["tags", "list[str]", false],
      ["old_string", "str", false],
      ["new_string", "str", false],
      ["replace_all", "bool", false],
      ["heading", "str", false],
      ["section_position", "str", false],
      ["edits", "json", false],
      ["row_key", "str", false],
      ["take", "str", false],
      ["overwrite", "bool", false],
      ["field", "str", false],
      ["value", "json", false],
      ["allow_curated", "bool", false],
      ["expected_hash", "str", false],
      ["validate_only", "bool", false],
    ],
    ["new_body", "new_string"],
  ],
  [
    "replace_memory",
    false,
    "write",
    1,
    "core",
    [
      ["old_path", "str", true],
      ["content", "str", true],
      ["title", "str", true],
      ["slug", "str", false],
      ["note_type", "str", false],
      ["reason", "str", false],
      ["project", "str", false],
      ["projects", "list[str]", false],
      ["sources", "list[str]", false],
      ["tags", "list[str]", false],
      ["status", "str", false],
      ["severity", "str", false],
      ["pattern_type", "str", false],
      ["domain", "str", false],
      ["started", "str", false],
      ["duration", "str", false],
      ["hypothesis", "str", false],
      ["n", "int", false],
      ["concluded", "str", false],
      ["medium", "str", false],
      ["recorded", "str", false],
      ["published", "str", false],
      ["host", "str", false],
      ["editor", "str", false],
      ["project_category", "str", false],
    ],
    ["content"],
  ],
  [
    "capture_source",
    false,
    "write",
    1,
    "core",
    [
      ["content", "str", true],
      ["title", "str", true],
      ["slug", "str", false],
      ["source_type", "str", false],
      ["url", "str", false],
      ["tags", "list[str]", false],
      ["why_captured", "str", false],
      ["compile_guidance", "bool", false],
      ["suggested_title", "str", false],
    ],
    ["content"],
  ],
  [
    "compile_source",
    true,
    "read",
    1,
    "core",
    [
      ["sources", "list[str]", true],
      ["suggested_title", "str", false],
    ],
    [],
  ],
  [
    "preserve_evidence",
    false,
    "write",
    1,
    "core",
    [
      ["scope", "str", true],
      ["category", "str", true],
      ["filename", "str", true],
      ["content", "str", true],
      ["description", "str", false],
    ],
    ["content"],
  ],
  ["transfer_artifact", false, "write", 1, "core", [["operation", "str", false]], []],
  [
    "review_memory",
    true,
    "read",
    1,
    "core",
    [
      ["mode", "str", false],
      ["categories", "list[str]", false],
      ["limit", "int", false],
      ["query", "str", false],
      ["sources", "list[str]", false],
      ["suggested_title", "str", false],
      ["tag", "str", false],
      ["key", "str", false],
      ["value", "str", false],
      ["path", "str", false],
      ["state", "str", false],
      ["ref", "str", false],
    ],
    [],
  ],
  [
    "review_item_context",
    true,
    "read",
    1,
    "core",
    [
      ["ref", "str", true],
      ["expected_fingerprint", "str", false],
      ["max_body_chars", "int", false],
      ["max_related_pages", "int", false],
      ["max_graph_nodes", "int", false],
      ["max_graph_edges", "int", false],
      ["max_history", "int", false],
      ["max_evolution_versions", "int", false],
    ],
    [],
  ],
  [
    "triage_memory",
    false,
    "write",
    1,
    "core",
    [
      ["ref", "str", true],
      ["action", "str", true],
      ["until", "str", false],
      ["why", "str", false],
      ["expected_fingerprint", "str", false],
    ],
    [],
  ],
  [
    "connect_memory",
    false,
    "write",
    1,
    "core",
    [
      ["operation", "str", false],
      ["path", "str", false],
      ["target", "str", false],
      ["query", "str", false],
      ["draft_title", "str", false],
      ["draft_body", "str", false],
      ["limit", "int", false],
      ["scope", "str", false],
      ["include_model_suggestions", "bool", false],
      ["depth", "int", false],
      ["relation_types", "list[str]", false],
      ["node_types", "list[str]", false],
      ["max_nodes", "int", false],
      ["max_edges", "int", false],
      ["traversal_profile", "str", false],
      ["max_body_chars", "int", false],
      ["entity_type", "str", false],
      ["name", "str", false],
      ["slug", "str", false],
      ["summary", "str", false],
      ["why_in_kb", "str", false],
      ["tags", "list[str]", false],
      ["connections", "list[str]", false],
      ["affiliation", "str", false],
      ["relationship", "str", false],
      ["domain", "str", false],
      ["language", "str", false],
      ["repo", "str", false],
      ["license", "str", false],
      ["used_in", "list[str]", false],
      ["decided", "str", false],
      ["project", "str", false],
      ["decision_status", "str", false],
      ["ref", "str", false],
      ["expected_hash", "str", false],
      ["why", "str", false],
      ["expected_fingerprint", "str", false],
    ],
    [],
  ],
  [
    "adopt_vault",
    false,
    "write",
    1,
    "core",
    [
      ["path", "str", false],
      ["mode", "str", false],
      ["max_depth", "int", false],
      ["include_hidden", "bool", false],
      ["samples", "int", false],
      ["pack_limit", "int", false],
      ["manifest_path", "str", false],
      ["selected_paths", "list[str]", false],
    ],
    [],
  ],
  [
    "maintain_memory",
    false,
    "write",
    1,
    "core",
    [
      ["mode", "str", false],
      ["categories", "list[str]", false],
      ["dry_run", "bool", false],
      ["rebuild_embeddings", "bool", false],
    ],
    [],
  ],
  [
    "schema_memory",
    false,
    "write",
    1,
    "core",
    [
      ["operation", "str", true],
      ["name", "str", false],
      ["subject", "str", false],
      ["project", "str", false],
      ["page_type", "str", false],
      ["save", "bool", false],
      ["expected_hash", "str", false],
      ["strict", "bool", false],
      ["compare_to", "str", false],
      ["proposal", "dict", false],
      ["include_model_suggestions", "bool", false],
    ],
    [],
  ],
  [
    "manage_memory_file",
    false,
    "write",
    2,
    "tier-2",
    [
      ["operation", "str", false],
      ["path", "str", false],
      ["content", "str", false],
      ["frontmatter", "dict", false],
      ["overwrite", "bool", false],
      ["allow_curated", "bool", false],
      ["kind", "str", false],
      ["parents", "bool", false],
      ["recursive", "bool", false],
      ["include_hidden", "bool", false],
      ["old_path", "str", false],
      ["new_path", "str", false],
      ["update_wikilinks", "bool", false],
      ["confirm", "bool", false],
      ["force_orphan", "bool", false],
      ["force_superseded", "bool", false],
      ["expected_dead_inbound", "list[str]", false],
      ["trash_path", "str", false],
      ["restore_path", "str", false],
      ["date", "str", false],
    ],
    ["content"],
  ],
  [
    "query_dataset",
    true,
    "read",
    2,
    "tier-2",
    [
      ["path", "str", true],
      ["record_path", "str", false],
      ["filters", "json", false],
      ["columns", "list[str]", false],
      ["sort_by", "str", false],
      ["descending", "bool", false],
      ["limit", "int", false],
      ["offset", "int", false],
      ["aggregate", "str", false],
      ["date_from", "str", false],
      ["date_to", "str", false],
      ["date_column", "str", false],
    ],
    [],
  ],
] as const satisfies readonly ExomemContractCommandFixture[];

export const exomemContractFixture0191 = {
  release: "0.19.1",
  protocol: "1",
  digest: "983c4447f77ef31c1109b565e0149e053d222d87adabb84d5b3bc3581d1dfee2",
  commands,
} as const;
